---
title: "House Prices - Advanced Regression Techniques"
author: "Hyejin Lee"
date: "2022-08-08"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

모던패밀리 필 던피로 빙의해서 집값 분석하기 

```{r}
library(tidyverse)
train <- read.csv("./house-prices/train.csv", header=T)
head(train)
```
## 행이 1460개, 열이 81개 인게 실화인가요?

```{r}
dim(train)
```
<내가 의미 있을 것이라고 생각했던 키워드와 컬럼>

1. 학군
2. 치안 -> Fence

```{r}
library("VIM")
library("ggplot2")
aggr(train$Fence, prop=FALSE, numbers=TRUE)
```

우선, 종속변수인 SalePrice의 히스토그램.</br>

```{r}
# saleprice 히스토그램
options(scipen=999)
hist(train$SalePrice,col = 'lightblue', border = 'black',
         main = 'SalePrice 히스토그램', xlab = 'SalePrice', ylab='count')
```

1.정규분포에서 살짝 벗어난다.</br>
2.데이터의 분포가 한쪽으로 쏠린 왜도 현상이 보인다.</br>

```{r}
# 상관계수 - 결측치 값 있음 

# 수치형 컬럼만 가져오기 
train_cor <- cor((train)[ ,sapply(train, class) == 'integer']) # 상관계수
round(train_cor[,38],1) # SalePrices기준으로 상관계수
```
가장 상관계수가 높은 TOP3

1. OverallQual (0.8)
2. GrLivArea   (0.7)
3. FullBath    (0.6)

```{r}
# 상관관계 그래프 
library("corrplot")
corrplot(train_cor)
```

# 1. OverallQual(전체 품질)

```{r}
plot(train$OverallQual, train$SalePrice, main='집값과 전체 품질(OverallQual)',
     xlab='전체 품질(등급)', ylab='집값', col='orange', pch=15,
     xlim=c(1,10))
```

컬럼 OverallQual은 집의 전반적인 재료와 마감을 평가.</br>
집의 전체 품질이 올라갈수록 집값이 올라가는 모습을 보임.</br>
특이한게 최고 등급인 10등급에서 다양한 가격의 분포를 볼 수 있음.</br>

# 2.GrLivArea(거실 면적) 

```{r}
# 이상치 처리 
outlier <- boxplot.stats(train$GrLivArea)$out
train.no.outlier <- train
train.no.outlier[train.no.outlier$GrLivArea %in% outlier, ] <- NA

plot(train.no.outlier$GrLivArea, train.no.outlier$SalePrice, 
     main='집값과 거실 면적', xlab='거실 면적(평방 피트)', 
     ylab='집값', col='blue', pch=15)
```

# 3. FullBath(욕실 수) 

```{r}
plot(factor(train$FullBath), train$SalePrice, main='집값과 욕실 수',
     xlab='욕실 수(0~3)', ylab='집값', col='green', pch=15)

library(dplyr)
MB <- train%>%
    group_by(FullBath)%>%
    summarise(meanBath=mean(SalePrice))
str(MB)
MB$FullBath<-as.factor(MB$FullBath)
barplot(MB$meanBath, names.arg = MB$FullBath, main='집값과 욕실 수',
        xlab='욕실 수(0~3)', ylab='집값', col='purple')
```
